"""empty message

Revision ID: 13d70fc715b
Revises: 230da6b577
Create Date: 2015-05-14 00:07:07.896878

"""

# revision identifiers, used by Alembic.
revision = '13d70fc715b'
down_revision = '230da6b577'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal', sa.Column('summary', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animal', 'summary')
    ### end Alembic commands ###
