"""empty message

Revision ID: 230da6b577
Revises: 52b7838eb54
Create Date: 2015-05-10 14:31:05.033534

"""

# revision identifiers, used by Alembic.
revision = '230da6b577'
down_revision = '52b7838eb54'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=264), nullable=True),
    sa.Column('picture_url', sa.String(length=264), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('animals')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=264), autoincrement=False, nullable=True),
    sa.Column('picture_url', sa.VARCHAR(length=264), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='animals_pkey')
    )
    op.drop_table('animal')
    ### end Alembic commands ###
