"""empty message

Revision ID: 2ef4e68c728
Revises: 13d70fc715b
Create Date: 2015-05-14 00:09:43.496458

"""

# revision identifiers, used by Alembic.
revision = '2ef4e68c728'
down_revision = '13d70fc715b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
