"""empty message

Revision ID: 2f135a8af42
Revises: 3a12c69850f
Create Date: 2015-05-10 06:43:09.985226

"""

# revision identifiers, used by Alembic.
revision = '2f135a8af42'
down_revision = '3a12c69850f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
