"""empty message

Revision ID: 3a12c69850f
Revises: 5a855646f82
Create Date: 2015-05-10 06:35:52.170593

"""

# revision identifiers, used by Alembic.
revision = '3a12c69850f'
down_revision = '5a855646f82'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
