"""empty message

Revision ID: 3dd84aebb3
Revises: 87a32c11c0
Create Date: 2015-05-10 12:37:40.281469

"""

# revision identifiers, used by Alembic.
revision = '3dd84aebb3'
down_revision = '87a32c11c0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=264), nullable=True),
    sa.Column('picture_url', sa.String(length=264), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animals')
    ### end Alembic commands ###
