"""empty message

Revision ID: 3e6d38ac9a7
Revises: 2f135a8af42
Create Date: 2015-05-10 06:52:19.753127

"""

# revision identifiers, used by Alembic.
revision = '3e6d38ac9a7'
down_revision = '2f135a8af42'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
