"""empty message

Revision ID: 4346361de74
Revises: 2ef4e68c728
Create Date: 2015-05-20 16:10:45.313750

"""

# revision identifiers, used by Alembic.
revision = '4346361de74'
down_revision = '2ef4e68c728'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
