"""empty message

Revision ID: 52b7838eb54
Revises: 3dd84aebb3
Create Date: 2015-05-10 12:40:59.200785

"""

# revision identifiers, used by Alembic.
revision = '52b7838eb54'
down_revision = '3dd84aebb3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
